host: http://localhost:8080/api/swagger/index.html
info:
  contact:
    name: nj-jay
  description: 接口文档
  title: mysql-gin-api接口文档
  version: "2.0"
paths:
  /api/v2/trueLogin:
    post:
      parameters:
      - description: 登录名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 登录接口
swagger: "2.0"
